version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - nilerr
    - nilnil
    - goconst
    - gocritic
    - gocognit
    - nestif
    - unparam
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocognit:
      min-complexity: 20
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 5

  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - gosec
          - goconst
          - gocognit

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
