version: 2

builds:
  - id: codeowner
    main: ./cmd/codeowner
    binary: codeowner
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/kevin-robayna/codeowner/internal/appinfo.Version={{.Version}}
      - -X github.com/kevin-robayna/codeowner/internal/appinfo.Commit={{.Commit}}
      - -X github.com/kevin-robayna/codeowner/internal/appinfo.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: codeowner-archive
    builds:
      - codeowner
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - name: codeowner
    repository:
      owner: kevinrobayna
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAPS_PAT }}"
    directory: Formula
    homepage: "https://github.com/kevinrobayna/codeowner"
    description: "A CLI tool for working with CODEOWNERS files"
    license: "MIT"
    install: |
      bin.install "codeowner"
    test: |
      system "#{bin}/codeowner", "version"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
