version: 2
gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
builds:
  - id: codeowner
    main: ./cmd/codeowner
    binary: codeowner
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/kevin-robayna/codeowner/internal/appinfo.Version={{.Version}}
      - -X github.com/kevin-robayna/codeowner/internal/appinfo.Commit={{.Commit}}
      - -X github.com/kevin-robayna/codeowner/internal/appinfo.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: codeowner-archive
    ids:
      - codeowner
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
signs:
  - cmd: cosign
    artifacts: all
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - '--yes'
    output: true
homebrew_casks:
  - name: codeowner
    binaries:
      - codeowner
    homepage: https://github.com/kevinrobayna/codeowner
    description: A CLI tool for working with CODEOWNERS files
    commit_msg_template: Brew cask update for {{ .ProjectName }} version {{ .Tag }}
    directory: Casks
    repository:
      owner: kevinrobayna
      name: homebrew-tap
      branch: main
      token: '{{ .Env.HOMEBREW_TAPS_PAT }}'
    commit_author:
      name: goreleaserbot
      email: github@kevinrobayna.com
