coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 95%

comment:
  layout: "reach,diff,flags,files"
  require_changes: true

ignore:
  - "cmd/**"
  - "internal/appinfo/**"
